#!/usr/bin/env ruby
# frozen-string-literal: true

Bundler.require :default
require 'json'
require 'yaml'
require 'digest'
require 'uri'
require 'open-uri'
require 'zlib'
require 'rubygems/package'
require 'fileutils'

def require_libs(libs) = libs.each { require_relative "lib/#{_1}" }

require_libs %w[
  globals
  options
  patches
  hooks
  db
  i18n
  configuration
  helpers
  xkcd
  tpdict
  sitelenpona
  tio
  pkgsearch
  breaking_wrap
  modules
  cli
  init
]

QBot.version = '7.11.0'
QBot.run!
