#!/usr/bin/env ruby
# frozen-string-literal: true

Bundler.require :default
require 'json'
require 'yaml'
require 'digest'
require 'uri'
require 'open-uri'

def require_libs(libs)
  libs.each { require_relative "lib/#{_1}" }
end

require_libs %w[
  globals
  options
  patches
  db
  i18n
  configuration
  helpers
  breaking_wrap
  modules
  cli
  init
]

QBot.version = '6.3.7'
QBot.run!
